### ISSUE TITLE
substract is an obsolete spelling of subtract.

### ISSUE THREAD

**Issue by thundergnat** [pierre-vigier/Perl6-Math-Matrix#1]
Substract is considered obsolete. Subtract is the generally accepted spelling. 

Cool module though. May be worth looking through the tasks on Rosetta code to find matrix operations to possibly include. http://rosettacode.org/wiki/Category:Programming_Tasks  Search on 'matrix', 'decomposition' and/or 'row echelon' for matrix related stuff.

**Comment by pierre-vigier** [comment]
Hi, thanks for the comment,

for subtract, i replaced substract by subtract, as i guess the module is not widely used yet, i did directly remove substract and use substract.

Indeed, new operations should be added, thanks for the sources

**Comment by lichtkind** [comment]
old spellign was removed
can be closed?

**Comment by pierre-vigier** [comment]
Hi, i kept it for the row echelon and other matrix stuff, but you are right, it's not forgotten, let's close it
