### ISSUE TITLE
constructor naming

### ISSUE THREAD

**Issue by lichtkind** [pierre-vigier/Perl6-Math-Matrix#17]
i just made a method for a submatrix (which i will need for def pos tester, which i need for choleski), there will be one to get the diagonal on so on. So when you write $matrix.submatrix or $marix.diagonal all is fine. But our current diagonal or zero and more i plan to do step a bit out of the scheme because $matrix.zero(...) creates a new which has nothing to do with the old.

thatswhy i propose as a first step to rename zero to new-zero($r,$c) which will be shortcut for new( :@size => ($r,$c), :$defaultvalue => 0).

**Comment by pierre-vigier** [comment]
I have some question about submatrix first, that you can see in the pull request, inline with code
But, it the direction, i agree.

Thanks

**Comment by lichtkind** [comment]
since you also prepare some changes i will now restrict myself and only propose here next constructor additions so we can complete that before stepping to accessors. when is that stable code wil shrink and get cleaner (as with my new trace method using diagonal accessor)

**Comment by lichtkind** [comment]
since you also prepare some changes i will now restrict myself and only propose here next constructor additions so we can complete that before stepping to accessors. when is that stable code wil shrink and get cleaner (as with my new trace method using diagonal accessor)

**Comment by lichtkind** [comment]
what i basically plan is an optional arbument rows and colums but as hash so  it can only hold some indexes but i want to clear first if we want to go 0 based or 1 based.

**Comment by pierre-vigier** [comment]
I can see the point of going on 1 indexing, however, we are still talking about perl, i think 0 makes more sense.
For instance, PDLA with Perl5 is indexing from 0 as well, and from what i have seem, so is numpy in python
