### ISSUE TITLE
table method

### ISSUE THREAD

**Issue by lichtkind** [pierre-vigier/Perl6-Math-Matrix#18]
I want a pretty print method like octave/mathematica has.
somthing that goes through all values swees which cell needs most space
and then sprintf every cell to that format so values are arrayd in columns and rows with big spaces.

I already have a simple version of the code but needs much refinement.
are you allright with the name?

**Comment by pierre-vigier** [comment]
What about pretty-print ?

**Comment by lichtkind** [comment]
table is not quite right but still mire descriptive.  why not overload fmt in some clever way?

**Comment by pierre-vigier** [comment]
In fact, i'm also thinking of pretty print because of your first statement, you said:
>  I want a pretty print method...
So i was thinking of pretty print, and it would do exactly that

**Comment by lichtkind** [comment]
and it is nice to look at but i dont know

**Comment by lichtkind** [comment]
after talking with #perl6 .gist has won, its the perl 6 standard for this,

btw we have to change .perl too to met perl 6 standards i do that today
