### ISSUE TITLE
Matrix in Num context?

### ISSUE THREAD

**Issue by lichtkind** [pierre-vigier/Perl6-Math-Matrix#23]
Thanks for quick reactions, I currently want to implement most  decompositions and just recently added bool context converter and the .Int give me somewhat headaches. naturally that would be cell count but I want o ask you before if you have any better ideaswhat +$matrix should return.

Thanks

**Comment by pierre-vigier** [comment]
What would the bool converter do? what is a "false" matrix?

For the Int method, the number of cells is a good idea, however, i am not sure we should implement it, let me give you a parallel with list:
```perl6
> my $list = (1,2,3);
(1 2 3)
> say $list
(1 2 3)
> say +$list
3
> say 10 + $list;
13
```

in case of a Matrix, a matrix + a scalar, does it make sense? like in adding that scalar to every cell of the matrix? 
I mean something like matrix A = 
1 2
3 4
doing [B] = [A] + 2 would give B = 
3 4
5 6

I'm not even sure that operation would make sense, but if it does, it would be in conflict with +A as to force numerical context

Eager to read you opinions

**Comment by lichtkind** [comment]
? test in all numeric domains for nullity like matrix does in my latest patch, jsut test:

?1  -> True
?0  -> False
?0.00 -> False
?(0+0i) -> False   but
?(0+i)   -> True 
since complex numbers are in cor ethis is the way to go for multi value numbers as quaterions or matrices.

please see that perl distinguishes between infix and prefix which binds higher. I at least thought we can achieve that 10 $ $list is = (11,12,13) but i dont even think thats desirable. since in normal perl 6 list + int = int + nr lsit elements.

**Comment by lichtkind** [comment]
i would like to see such an op like  [B] = [A] + 2 but with some extra syntax (square brackets?) to make sure that something unusual/ in special context is happening

**Comment by pierre-vigier** [comment]
But what you were saying is right, infix Matrix + Numeric or Numerix + Matrix
And prefix +
I can take care of the infix without any issue, i am still confused with the prefix one, i let you implement it.
Seeing the implementation should make my doubts go away

**Comment by lichtkind** [comment]
yes we have to test this further, at some point dev speed will settle anyway :)

**Comment by lichtkind** [comment]
I see this part of a bigger problem, because once i wanted to get with ||$matrix||2 several norm which would be doable with  category of prefix_circumfix_meta_operator. similar someting like $matrix + [[2]] would make sense to be but im still not convinced its the best solution.

**Comment by lichtkind** [comment]
alright since this was just about the method Int, which is now in i close this for now
