### ISSUE TITLE
diagonally dominant

### ISSUE THREAD

**Issue by pierre-vigier** [pierre-vigier/Perl6-Math-Matrix#26]
I am trying too make a lot of thing lazy and computed only once.
I have a concern about is-diagonally-dominant, it has the name of an attribute, however it takes parameters, we should probably either create 6 differents lazy attributes, or change that to a method name, i mean no is-something

One solution might be to expose 6 lazy attributes and make them call the previous diagonally-dominant with correspondant parameter, and make that method private

  method is-diagonally-dominant(Math::Matrix:D: Bool :$strict = False, Str :$along where {$^orient eq any <column row both>} = 'column' --> Bool) {

**Comment by lichtkind** [comment]
both is rather unusual and can esily combined if we have the other two which actually need computing, but im too close before exam to think about that now I just do now decomp as part of preparation

**Comment by lichtkind** [comment]
I think current solution is good enough until we run into concrete issues
