### ISSUE TITLE
No matrix multiplication?

### ISSUE THREAD

**Issue by colomon** [pierre-vigier/Perl6-Math-Matrix#32]
Hi,

I'm unable to find a method here for basic matrix multiplication?  There are two multiply methods, but one is scalar times matrix multiplication, and the other is a weird element-by-element pairwise multiplication.  I couldn't find proper matrix multiplication [1] anywhere in there.  It is a very puzzling thing to be missing?  Am I just misunderstanding something?

[1] https://en.wikipedia.org/wiki/Matrix_multiplication

**Comment by pierre-vigier** [comment]
Here you have it:
https://github.com/pierre-vigier/Perl6-Math-Matrix#method-dotproduct
