### ISSUE TITLE
How to get row sum?

### ISSUE THREAD

**Issue by W4anD0eR96** [pierre-vigier/Perl6-Math-Matrix#33]
that is, 
[[ 0.  1.  1.  1.]
 [ 1.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  1.  0.]]
get
[3, 2, 1, 2]

so the column sum?

**Comment by W4anD0eR96** [comment]
find it like `dd $A dot Math::Matrix.new([[1],[1],[1],[1]]);`

**Comment by W4anD0eR96** [comment]
then .. how to norm one line?
as the example above
get
[[ 0. 1/3. 1/3. 1/3.]
[ 1/2. 0. 0. 1/2.]
[ 1. 0. 0. 0.]
[ 0. 1/2. 1/2. 0.]]

**Comment by lichtkind** [comment]
than cries to have some meta op and + is just one parameter for that i think about it

**Comment by lichtkind** [comment]
thanks for your trust but i prefer to let it open to remind me to actually do it :)

**Comment by lichtkind** [comment]
I just now implement reduce-rows and reduce-columns (reduce cells might come too) so your answer will be $matrix.reduce-rows( &[+] );

**Comment by W4anD0eR96** [comment]
thanks!
