### ISSUE TITLE
error installing Math::Matrix

### ISSUE THREAD

**Issue by wtwt5237** [pierre-vigier/Perl6-Math-Matrix#64]
Hello!

Could you please help me with this error message that happened when I installed Math::Matrix?

[twang6@Nucleus005 script]$ zef install Math::Matrix
===> Searching for: Math::Matrix
===> Searching for missing dependencies: AttrX::Lazy, Test::META
===> Searching for missing dependencies: META6, URI, License::SPDX
===> Searching for missing dependencies: JSON::Class, JSON::Class:ver<0.0.5+>, JSON::Fast
===> Searching for missing dependencies: JSON::Marshal, JSON::Unmarshal
===> Searching for missing dependencies: JSON::Name
===> Testing: AttrX::Lazy:ver<0.0.3>
===> Testing [OK] for AttrX::Lazy:ver<0.0.3>
===> Testing: JSON::Fast:ver<0.10>
===> Testing [OK] for JSON::Fast:ver<0.10>
===> Testing: JSON::Name:ver<0.0.4>:authgithub:jonathanstowe:api<1.0>
===> Testing [OK] for JSON::Name:ver<0.0.4>:authgithub:jonathanstowe:api<1.0>
===> Testing: JSON::Marshal:ver<0.0.18>:authgithub:jonathanstowe:api<1.0>
===> Testing [OK] for JSON::Marshal:ver<0.0.18>:authgithub:jonathanstowe:api<1.0>
===> Testing: JSON::Unmarshal:ver<0.08>
===> Testing [OK] for JSON::Unmarshal:ver<0.08>
===> Testing: JSON::Class:ver<0.0.13>:authgithub:jonathanstowe:api<1.0>
===> Testing [OK] for JSON::Class:ver<0.0.13>:authgithub:jonathanstowe:api<1.0>
===> Testing: META6:ver<0.0.23>:authgithub:jonathanstowe:api<1.0>
===> Testing [OK] for META6:ver<0.0.23>:authgithub:jonathanstowe:api<1.0>
===> Testing: URI:ver<0.3.0>
===> Testing [OK] for URI:ver<0.3.0>
===> Testing: License::SPDX:ver<3.7.0>:authgithub:jonathanstowe:api<1.0>
===> Testing [OK] for License::SPDX:ver<3.7.0>:authgithub:jonathanstowe:api<1.0>
===> Testing: Test::META:ver<0.0.16>:authgithub:jonathanstowe:api<1.0>
[Test::META] # the following may make some diagnostics from the module itself
===> Testing [OK] for Test::META:ver<0.0.16>:authgithub:jonathanstowe:api<1.0>
===> Testing: Math::Matrix:ver<0.3.8>:authgithub:pierre-vigier
**[Math::Matrix] Cannot modify an immutable Rat (3.142857)
[Math::Matrix] in block at /home2/twang6/.zef/store/Perl6-Math-Matrix.git/f1d54489e787d8b5f440d3cf094c71faabc07533/lib/Math/Matrix.pm6 (Math::Matrix) line 633
[Math::Matrix] in method LU-decomposition at /home2/twang6/.zef/store/Perl6-Math-Matrix.git/f1d54489e787d8b5f440d3cf094c71faabc07533/lib/Math/Matrix.pm6 (Math::Matrix) line 627
[Math::Matrix] in block at t/041-decomposition.t line 26
[Math::Matrix] # You planned 16 tests, but ran 4
===> Testing [FAIL]: Math::Matrix:ver<0.3.8>:authgithub:pierre-vigier
Aborting due to test failure: Math::Matrix:ver<0.3.8>:authgithub:pierre-vigier (use --force-test to override)**

Environment
Operating system: redhat 7.4
Compiler version (perl6 -v): This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1
implementing Perl 6.d.

 I tried --force-test to override, but got another error:

[twang6@Nucleus005 script]$ zef install --force-test Math::Matrix
===> Searching for: Math::Matrix
===> Searching for missing dependencies: AttrX::Lazy, Test::META
===> Searching for missing dependencies: META6, URI, License::SPDX
===> Searching for missing dependencies: JSON::Class, JSON::Class:ver<0.0.5+>, JSON::Fast
===> Searching for missing dependencies: JSON::Marshal, JSON::Unmarshal
===> Searching for missing dependencies: JSON::Name
===> Testing: AttrX::Lazy:ver<0.0.3>
===> Testing [OK] for AttrX::Lazy:ver<0.0.3>
===> Testing: JSON::Fast:ver<0.10>
===> Testing [OK] for JSON::Fast:ver<0.10>
===> Testing: JSON::Name:ver<0.0.4>:authgithub:jonathanstowe:api<1.0>
===> Testing [OK] for JSON::Name:ver<0.0.4>:authgithub:jonathanstowe:api<1.0>
===> Testing: JSON::Marshal:ver<0.0.18>:authgithub:jonathanstowe:api<1.0>
===> Testing [OK] for JSON::Marshal:ver<0.0.18>:authgithub:jonathanstowe:api<1.0>
===> Testing: JSON::Unmarshal:ver<0.08>
===> Testing [OK] for JSON::Unmarshal:ver<0.08>
===> Testing: JSON::Class:ver<0.0.13>:authgithub:jonathanstowe:api<1.0>
===> Testing [OK] for JSON::Class:ver<0.0.13>:authgithub:jonathanstowe:api<1.0>
===> Testing: META6:ver<0.0.23>:authgithub:jonathanstowe:api<1.0>
===> Testing [OK] for META6:ver<0.0.23>:authgithub:jonathanstowe:api<1.0>
===> Testing: URI:ver<0.3.0>
===> Testing [OK] for URI:ver<0.3.0>
===> Testing: License::SPDX:ver<3.7.0>:authgithub:jonathanstowe:api<1.0>
===> Testing [OK] for License::SPDX:ver<3.7.0>:authgithub:jonathanstowe:api<1.0>
===> Testing: Test::META:ver<0.0.16>:authgithub:jonathanstowe:api<1.0>
[Test::META] # the following may make some diagnostics from the module itself
===> Testing [OK] for Test::META:ver<0.0.16>:authgithub:jonathanstowe:api<1.0>
===> Testing: Math::Matrix:ver<0.3.8>:authgithub:pierre-vigier
[Math::Matrix] Cannot modify an immutable Rat (3.142857)
[Math::Matrix] in block at /home2/twang6/.zef/store/Perl6-Math-Matrix.git/f1d54489e787d8b5f440d3cf094c71faabc07533/lib/Math/Matrix.pm6 (Math::Matrix) line 633
[Math::Matrix] in method LU-decomposition at /home2/twang6/.zef/store/Perl6-Math-Matrix.git/f1d54489e787d8b5f440d3cf094c71faabc07533/lib/Math/Matrix.pm6 (Math::Matrix) line 627
[Math::Matrix] in block at t/041-decomposition.t line 26
[Math::Matrix] # You planned 16 tests, but ran 4
===> Testing [FAIL]: Math::Matrix:ver<0.3.8>:authgithub:pierre-vigier
[Math::Matrix] Failed to get passing tests, but continuing with --force-test
===> Installing: AttrX::Lazy:ver<0.0.3>
===> Installing: JSON::Fast:ver<0.10>
===> Installing: JSON::Name:ver<0.0.4>:authgithub:jonathanstowe:api<1.0>
===> Installing: JSON::Marshal:ver<0.0.18>:authgithub:jonathanstowe:api<1.0>
===> Installing: JSON::Unmarshal:ver<0.08>
===> Installing: JSON::Class:ver<0.0.13>:authgithub:jonathanstowe:api<1.0>
===> Installing: META6:ver<0.0.23>:authgithub:jonathanstowe:api<1.0>
===> Installing: URI:ver<0.3.0>
===> Installing: License::SPDX:ver<3.7.0>:authgithub:jonathanstowe:api<1.0>
===> Installing: Test::META:ver<0.0.16>:authgithub:jonathanstowe:api<1.0>
===> Installing: Math::Matrix:ver<0.3.8>:authgithub:pierre-vigier
**===> Install [FAIL] for Math::Matrix:ver<0.3.8>:authgithub:pierre-vigier: ===SORRY!===
Could not find Math::Matrix::Type at line 2 in:
inst#/home2/twang6/software/languages/raku/share/perl6/site
inst#/home2/twang6/software/languages/raku/share/perl6/vendor
inst#/home2/twang6/software/languages/raku/share/perl6/core
ap#
nqp#
perl5#**

**===SORRY!===
Could not find Math::Matrix::Type at line 2 in:
inst#/home2/twang6/software/languages/raku/share/perl6/site
inst#/home2/twang6/software/languages/raku/share/perl6/vendor
inst#/home2/twang6/software/languages/raku/share/perl6/core
ap#
nqp#
perl5#**

**Comment by lichtkind** [comment]
my bad, I know the source and will be fixed soon, as soon you see here version bump you will know its fixed

**Comment by lichtkind** [comment]
thanks for your trust but i will close issue when its actually fixed

**Comment by JJ** [comment]
Found again this error, with Raku 2019.11

**Comment by JJ** [comment]
Well, I have been trying to debug this, and it really beats me. It's really creating Rats, which are immutable, but the container (an array) shouldn't be. Somewhere along the line it's being itemized, or who knows, because normal Rats in normal (2-d) arrays can be smashed by any other value. So I don't really know. Might be a bug, but again, beats me.

**Comment by lichtkind** [comment]
sorry for late reply yes i know the source, wasnt that well last days i will fix it

**Comment by JJ** [comment]
@lichtkind there's a PR that fixes it also.

**Comment by lichtkind** [comment]
what is an PR?

**Comment by JJ** [comment]
Pull request #66
