### ISSUE TITLE
new internals

### ISSUE THREAD

**Issue by lichtkind** [pierre-vigier/Perl6-Math-Matrix#7]
Thanks for merges.
But the further I think about efficiency, certain hard to calculate properties should cached. So we need a mechanism to mark the value dirty if things change or we set it a policy to create a new object when a value changes.

second issue is we need a column iterator, not only for certain norms.

Please explain why exactly you need the row objekt.

Is a cooperation with Math::Vector planned?

plese set the trevis rights on your account so the status can be seen under modules.perl6.org.

thats all for now :)

(my next goal is a bool method for positive definite and choleski decomposition, maybe LU and LUP)

cheers
herbert

**Comment by pierre-vigier** [comment]
Hi,

For the integration with Math::Vector, i have nothing against, nor for. As a vector is only a matrix 1 x n or n x 1 , what does it gives more to use a Vector class?

The reason i created a class row is the following, let's imagine i do not have class row, and someone is playing with [] accessor.
I would only redifine method AT-POS() to return @!rows[$index]
However, with the first implementation i had @!rows was mutable, then a user could change a line of the matrix by a line with less or more columns. However, at the time i am writing this i realize that i do not have that issue anymore, so i can drop the Row object, it does not make any sense anymore, and just serve to slow down performance.

Pierre

**Comment by pierre-vigier** [comment]
There is still one issue, you can affect whatever you want to a cell of a Matrix:

my $matrix = Math::Matrix.new([[1,2],[3,4]]);
$matrix[0][0] = "a";

But it's not solve by Row anyway

**Comment by pierre-vigier** [comment]
Reopening concerning the dirty, cache and calculation

**Comment by pierre-vigier** [comment]
For the Travis, i did not find any settings in my account for that, if you have more info, i'm glad to listen to them

**Comment by lichtkind** [comment]
allright this looks serious lets fix the rewrite cells problem first

**Comment by lichtkind** [comment]
cograts you fixed that one: http://modules.perl6.org/

**Comment by pierre-vigier** [comment]
To be honest, i have no idea how, i checked a bit on #perl6 IRC , no body had any clues, the only thing i did was to remove blank lines from my .travis.yml file

**Comment by lichtkind** [comment]
i will look into the position-At thing but one way of solving it, could be to mark the values as dirty or delete them when you acess the matrix cells this way. another way to approach is the functional: that whenever something changes we create new object so that once created object is imutable. i just want that we make a decision here.   Thanks

**Comment by pierre-vigier** [comment]
I did some test by making @.rows an Array of Array[Numeric] , it would work and actually is working for the following case:
```perl6
my $m = Matrix.new([[1,2],[3,4]]);
$m[0][0] = "a";
```
Where i get a 
```perl6
Type check failed in assignment to @row; expected Numeric but got Str
  in block <unit> at t.pl line 13
```
However, it does not solve the problem to make the property dirty, hence i discarded that solution.
What we need is just a way to know when someone is accessing a cell for writing, i did not find a solution yet. If you have any idea, feel free to share, i have no problem to get the $m[0] but $m[0][something] , i have no idea yet....

**Comment by pierre-vigier** [comment]
# First, some solutions:

After some research, tests, and time on IRC, i have 2/3 solutions:
WE can make the matrix immutable with the following:
```perl6
my role immutable_list {
    method ASSIGN-POS(|) { fail "immutable!" };
}

multi method AT-POS( Math::Matrix:D: Int $index ) {
    fail X::OutOfRange.new(
        :what<Row index> , :got($index), :range("0..{$.row-count -1 }")
    ) unless 0 <= $index < $.row-count;
    #my $row = @!rows[$index].List;
    my $row = @!rows[$index];
    $row does immutable_list;
    return $row;
}
```
Which fail without dying on affectation of one cell. Change fail to die if it has to be fatal.

Still with immutability, the second solution i have is to transform the [] of Matrix to return a list with:
```perl6
multi method AT-POS( Math::Matrix:D: Int $index ) {
    fail X::OutOfRange.new(
        :what<Row index> , :got($index), :range("0..{$.row-count -1 }")
    ) unless 0 <= $index < $.row-count;
    my $row = @!rows[$index].List;
    return $row;
}
```
In that case, it dies with
```
 Cannot modify an immutable Int
  in block <unit> at t.pl line 13
```

With the role solution, we are able to catch the affection, and if we rewrite the Proxy container in the role of the list, we might be able to as well manage dirtying things.

# Now, some other considerations:
For now, the library is using Array of Array, and at one point, it should use shaped array, which are better adapted for that, but some parts are not implemented yet, and as it is today, it's slower than Array of Array.
my concern there is future compatibility break, Shaped Array use @a[row;column] notation, where Array of Array can use @a[row][column] , that methods, at least for now is not working on shaped arrays.
Until further development of shaped arrays, it is a bit "blocking", one solution however, not the cleanest, but it will work, and it allows us to switch internal without worrying for now, is to create an accessor cell
```perl6
my $matrix = Math::Matrix.diagonal(1,2,3);
say $matrix.cell(1,1); #displays 2
```
I will create that accessor for now, without modifying the doc yet, it is offcourse open to discussion, but immutability of the matrix and an accessor is what i would go for, at least first.

Going from immutable to mutable is possible, where the reverse will break compatibility

**Comment by lichtkind** [comment]
great i have to do homework now, just added some norms, next will be cholesky decomposition but that would imply having a positive definite tester which easiest to implement if we have eigenvalues :), 

With the oo: I maybe saw a different way to write a custom built method that would allow to have a completely private @!rows. But its not tested yet.

**Comment by lichtkind** [comment]
i like your idea to have accesor method instead of matrix[..][..] because so we dont even give the impression to direct acess and are more flexible with API anyway

**Comment by lichtkind** [comment]
im not convinced it would work somehow without your providing-private-accessor but what we need are iterators culumn wise and for the diagonal.

furthermore i would like to rename the diagonal to new-diagonal zero to new-zero and so forth and add a new-vector-product. And (after my upcoming exam) i want to extend the new method with optional hash parameter so you can insert single rows or columns or even single cells to minimize definition os sparse matrices. beside splitting and joining matrices i think it would be good to have a function to create a minor(matrix without certain row and column) and a somewhat cookie cutter like in : i want the partial matrix from 1;1 to 3;3. there are function who built upon this.

these are all rather basic ops but they would help to refactor/shrink a lot of what we already have and give a solid base for what mathematicians need.

cheers

**Comment by pierre-vigier** [comment]
I have already in local a function function to extract a matrix from a top left to bottom right cell, not pushed yet, as i was first trying to clean a bit the attributes, i wanted to remove the public ones (i kept them public only for equal, addition, those kind of methods)
Still, i would use different new function, using multi method instead of optional arguments, because some of those arguments will be mutually exclusive.

The one i have in mind are:
* new( :@row-vector )
* new( :@column-vector )
* new( :$identity ) where identity is the size of the matrix
* new( :$zero ) for zero matrix
* new( :@diagonal ) for diagonal matrix, i tend to not like short name like diag, i have seen so many case in day to day work where abbreviations get misunterpreted

However, for sparse Matrix, i have no idea of a single signature to create that, i'm eager to listen to your view for that one.

Can you explain a bit more what you would like for row iterator and column iterator?
row iterator loops through a list of rows , column iterator loops through columns, give matrices of 1 x n [[1],[2],[3]] ?

I am required to stay in bed because of some back issues, so i have time to work on those, happy to hear your comment on those points, before doing too much

Cheers

**Comment by lichtkind** [comment]
Best wishes for your health,

before the new new method I would like to try an alternative to get same result without additional module (private accessor). If that's stable or decided lets go to the constructors. What you wrote was my initial idea too but the more I think about,  e.g. want that method diagonal returns you the diagonal values. new-diagonal(.....) creates it which will be an alias to new(:diagonal = ....); i want to make the general new method a powertool and new-.... safe subsets. some detaisl are  still unclear but i want to get a dry and cut soultion for the acessors first. if we have there we get iterator (i would like to call them mmap or something like that for rowwise and columswise, or cellwise calculation). this would also shrink a lot of code.

Best

**Comment by lichtkind** [comment]
Allright i made a quick test:

unit class Math::V;
has @!cells is required;

method new (@c)               { self.bless( cls => @c) }
submethod BUILD( :@cls ) {   @!cells = @cls }
method sum(--> Numeric)  {    [+] @!cells   }

and on other side


my $v = Math::V.new([1,2,3]);
say $v.sum;
say $v!cells;

which works except the forbidden access,
and we could use

https://design.perl6.org/S12.html#Private_methods

so is there any other use case i overlooked we need the module for private accessors?

thank you and very best

**Comment by pierre-vigier** [comment]
Actually, what you are proposing here is what i did a few commit ago in that commit:
https://github.com/pierre-vigier/Perl6-Math-Matrix/commit/e7b6746f595e1e21f9356e00e09944011634c3dd

As you have seen you code does not allow to access a private attribute which is normal. The private accessor i created are not for that, let's take a really simple example,
One class Cell , with has a private value, $!value. and we want to implement a Cell.equal( another cell method ), the first idea is that:
```perl6
class Cell {
    has $!value is required;
    method new ($value) { self.bless( :$value ) }
    submethod BUILD( :$value ) { $!value = $value }
    method equal( Cell:D: $other ) {
        $!value == $other!value;
    }
}

my $a = Cell.new(5);
my $b = Cell.new(5);
say $a.equal( $b );
```

So in method equal, i need to check the value of another instance of the same class (we need that for Math::Matrix in equal, add, subtract, and a few others). However, a private attribute is only accessible to the instance itself, the previous code gives that output:
```
===SORRY!=== Error while compiling class3.pl
No such private method 'value' for invocant of type 'Cell'
at class3.pl:6
------>         $!value == $other!⏏value;
```
Solution for that, add a "private read accessor", with a private method:
```perl6
class Cell {
    has $!value is required;
    method new ($value) { self.bless( :$value ) }
    submethod BUILD( :$value ) { $!value = $value }
    method !value() { $!value }
    method equal( Cell:D: $other ) {
        $!value == $other!value;
    }
}

my $a = Cell.new(5);
my $b = Cell.new(5);
say $a.equal( $b );
```
then output is:
```
True
````

The module AttrX::PrivateAccessor is just a syntaxic sugar
```perl6
class Cell {
    has $!value is providing-private-accessor;
}
```
is the same as 
```perl6
class Cell {
    has $!value;
    method !value() {$!value}
}
```

However, the module Attrx::PrivateAccessor has some big issues in some cases, so i'll remove the dependency and declare the private method manually until i find a way to fix the module properly.

Cheers

**Comment by lichtkind** [comment]
thank you for explaining, i understand now the problem, there might be even another solution but i have to think it through first

**Comment by pierre-vigier** [comment]
I'm thinking of switching everything to list of List, without changing the outside interface.
flattening of Array is much "stranger" than flattening of list.
I might try on a separate branch at first

**Comment by lichtkind** [comment]
sorry but i could not understand you message, neither the consequences :)

**Comment by pierre-vigier** [comment]
Right now we are using Array of Array internally, which does not play well with flattening:
```perl
> my @array-of-array = [ [1,2],[3,4] ];
[[1 2] [3 4]]
> my $list-of-list = ( (1,2),(3,4) );
((1 2) (3 4))
> say @array-of-array.flat
([1 2] [3 4])
> say $list-of-list.flat
(1 2 3 4)
>
```

Flattening would help in some cases, and it would avoid some.
Also using list would avoid some unecessary looking [], like `[ @rows.map( { [ @!rows[$_][|@cols] ] } ) ]`

However, for flattening to check all the values, as the number of dimensions is always 2, @array[*;*] seems to be working

Anyway, if i test something, it will first be in a separate branch, and should not break any tests, without changing tests, naturaaly

**Comment by lichtkind** [comment]
i will give AT-POS another try even is is awkward to make array like acess readonly, mabye use our own postcircumfix op. this would be consitent with latest converter into AoA context. something like $matrix<1,2> ?

**Comment by lichtkind** [comment]
as rational arrays have [] hashes indexes {} so we have to have our own. on the other sider {} is Str and inside [] are numericals

**Comment by lichtkind** [comment]
i think with current desugn its decided how got about discussed questions plus there is still the native shape issue so I can close this
